language: python
sudo: false

matrix:
    include:
        - python: 2.7
        - python: 3.4

install:
   - pip install -r dev_requirements.txt;
   - python setup.py develop

script:
  - coverage run -m haas zipfile2
  - coverage report

notifications:
  email:
    - cournape@gmail.com
